ARG IMAGE_NAME_DEPS=aisearch-deps-base:latest
ARG REGISTRY=localhost:5001
# Dockerfile
FROM ${REGISTRY}/${IMAGE_NAME_DEPS}

ARG http_proxy
ARG https_proxy
ARG HTTP_PROXY
ARG HTTPS_PROXY

ENV http_proxy=${http_proxy} https_proxy=${https_proxy}\
    HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTPS_PROXY}

WORKDIR /backend

COPY pyproject.toml ./

RUN uv pip compile pyproject.toml -o requirements.lock \
 && uv pip sync --system requirements.lock

COPY . /backend/

ENV PYTHONPATH=/backend \
    http_proxy='' https_proxy=''\
    HTTPS_PROXY='' HTTP_PROXY=''
