FROM python:3.12-slim

ARG http_proxy=""
ARG https_proxy=""
ARG HTTP_PROXY=""
ARG HTTPS_PROXY=""

ENV DEBIAN_FRONTEND=noninteractive TZ=Europe/Moscow \
    http_proxy=${https_proxy} https_proxy=${http_proxy}\
    HTTPS_PROXY=${HTTPS_PROXY} HTTP_PROXY=${HTTP_PROXY}

RUN apt-get update && \
    apt-get install -y --no-install-recommends postgresql-client curl redis-tools jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /backend

RUN pip install --upgrade pip uv

COPY pyproject.toml ./pyproject.toml

RUN uv pip compile pyproject.toml --extra api -o requirements.lock \
 && uv pip sync --system requirements.lock

ENV http_proxy='' https_proxy='' HTTPS_PROXY='' HTTP_PROXY=''
