ARG IMAGE_NAME_DEPS=aisearch-deps-base:latest
ARG REGISTRY=localhost:5001
FROM ${REGISTRY}/${IMAGE_NAME_DEPS}

ARG https_proxy
ARG http_proxy
ARG HTTP_PROXY
ARG HTTPS_PROXY

ENV http_proxy=${http_proxy} https_proxy=${https_proxy}\
    HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTPS_PROXY}

WORKDIR /backend

COPY pyproject.toml ./pyproject.toml

RUN uv pip compile pyproject.toml -o requirements.lock --extra search \
 && uv pip sync --system requirements.lock

ENV  http_proxy=''  https_proxy='' \
     HTTP_PROXY='' HTTPS_PROXY='' \
     PYTHONPATH=/backend
