FROM python:3.12-slim

WORKDIR /backend

RUN pip install --upgrade pip uv

COPY buildeps/queue/pyproject.toml ./buildeps/queue/pyproject.toml

RUN uv pip compile buildeps/queue/pyproject.toml -o requirements.lock \
 && uv pip sync --system requirements.lock

