"""initial

Revision ID: be6da433bd0a
Revises: 
Create Date: 2025-11-14 16:27:44.377495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be6da433bd0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')
    sa.Enum('LIKE', 'DISLIKE', name='rating_enum').create(op.get_bind())
    op.create_table('search_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('search_start_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('full_execution_time', sa.Integer(), nullable=False),
    sa.Column('search_execution_time', sa.Integer(), nullable=False),
    sa.Column('dense_search_time', sa.Integer(), nullable=False),
    sa.Column('lex_search_time', sa.Integer(), nullable=False),
    sa.Column('query_norm_time', sa.Integer(), nullable=False),
    sa.Column('reranker_time', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=500), nullable=False),
    sa.Column('reranker_name', sa.String(length=500), nullable=False),
    sa.Column('reranker_enable', sa.Boolean(), nullable=False),
    sa.Column('lex_enable', sa.Boolean(), nullable=False),
    sa.Column('from_cache', sa.Boolean(), nullable=False),
    sa.Column('lex_candidate', sa.String(length=500), nullable=True),
    sa.Column('dense_top_k', sa.Integer(), nullable=False),
    sa.Column('lex_top_k', sa.Integer(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('weight_ce', sa.Float(), nullable=False),
    sa.Column('weight_dense', sa.Float(), nullable=False),
    sa.Column('weight_lex', sa.Float(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name='unique_search_request_id')
    )
    op.create_index('ix_search_request_created_at_asc', 'search_request', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'ASC'})
    op.create_index('ix_search_request_created_at_desc', 'search_request', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index('ix_search_request_dense_search_time', 'search_request', ['dense_search_time'], unique=False, postgresql_using='btree')
    op.create_index('ix_search_request_dense_top_k', 'search_request', ['dense_top_k'], unique=False, postgresql_using='btree')
    op.create_index('ix_search_request_from_cache', 'search_request', ['from_cache'], unique=False, postgresql_using='btree')
    op.create_index('ix_search_request_full_execution_time', 'search_request', ['full_execution_time'], unique=False, postgresql_using='btree')
    op.create_index('ix_search_request_lex_candidate_gin_trgm', 'search_request', ['lex_candidate'], unique=False, postgresql_using='gin', postgresql_ops={'lex_candidate': 'gin_trgm_ops'})
    op.create_index('ix_search_request_lex_enable', 'search_request', ['lex_enable'], unique=False, postgresql_using='btree')
    op.create_index('ix_search_request_lex_search_time', 'search_request', ['lex_search_time'], unique=False, postgresql_using='btree')
    op.create_index('ix_search_request_lex_top_k', 'search_request', ['lex_top_k'], unique=False, postgresql_using='btree')
    op.create_index('ix_search_request_model_name_gin_trgm', 'search_request', ['model_name'], unique=False, postgresql_using='gin', postgresql_ops={'model_name': 'gin_trgm_ops'})
    op.create_index('ix_search_request_modified_at_asc', 'search_request', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'ASC'})
    op.create_index('ix_search_request_modified_at_desc', 'search_request', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.create_index('ix_search_request_query_gin_trgm', 'search_request', ['query'], unique=False, postgresql_using='gin', postgresql_ops={'query': 'gin_trgm_ops'})
    op.create_index('ix_search_request_query_norm_time', 'search_request', ['query_norm_time'], unique=False, postgresql_using='btree')
    op.create_index('ix_search_request_reranker_enable', 'search_request', ['reranker_enable'], unique=False, postgresql_using='btree')
    op.create_index('ix_search_request_reranker_name_gin_trgm', 'search_request', ['reranker_name'], unique=False, postgresql_using='gin', postgresql_ops={'reranker_name': 'gin_trgm_ops'})
    op.create_index('ix_search_request_reranker_time', 'search_request', ['reranker_time'], unique=False, postgresql_using='btree')
    op.create_index('ix_search_request_results_jsonb_path', 'search_request', ['results'], unique=False, postgresql_using='gin', postgresql_ops={'results': 'jsonb_path_ops'})
    op.create_index('ix_search_request_search_execution_time', 'search_request', ['search_execution_time'], unique=False, postgresql_using='btree')
    op.create_index('ix_search_request_search_start_time_asc', 'search_request', ['search_start_time'], unique=False, postgresql_using='btree', postgresql_ops={'search_start_time': 'ASC'})
    op.create_index('ix_search_request_search_start_time_desc', 'search_request', ['search_start_time'], unique=False, postgresql_using='btree', postgresql_ops={'search_start_time': 'DESC'})
    op.create_index('ix_search_request_top_k', 'search_request', ['top_k'], unique=False, postgresql_using='btree')
    op.create_index('ix_search_request_weight_ce', 'search_request', ['weight_ce'], unique=False, postgresql_using='btree')
    op.create_index('ix_search_request_weight_dense', 'search_request', ['weight_dense'], unique=False, postgresql_using='btree')
    op.create_index('ix_search_request_weight_lex', 'search_request', ['weight_lex'], unique=False, postgresql_using='btree')
    op.create_table('knowledge_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_request_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=500), nullable=False),
    sa.Column('rating', postgresql.ENUM('LIKE', 'DISLIKE', name='rating_enum', create_type=False), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_request_id'], ['search_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_request_id', 'question_id', name='unique_knowledge_feedback_request_question')
    )
    op.create_index('idx_knowledge_feedback_comment_gin', 'knowledge_feedback', ['comment'], unique=False, postgresql_using='gin', postgresql_ops={'comment': 'gin_trgm_ops'})
    op.create_index('idx_knowledge_feedback_created_at_asc', 'knowledge_feedback', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'ASC'})
    op.create_index('idx_knowledge_feedback_created_at_desc', 'knowledge_feedback', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_knowledge_feedback_id_search_request_id', 'knowledge_feedback', ['id', 'search_request_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_knowledge_feedback_modified_at_asc', 'knowledge_feedback', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'ASC'})
    op.create_index('idx_knowledge_feedback_modified_at_desc', 'knowledge_feedback', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.create_index('idx_knowledge_feedback_question_id', 'knowledge_feedback', ['question_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_knowledge_feedback_search_request_id', 'knowledge_feedback', ['search_request_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_knowledge_feedback_search_request_id_question_id', 'knowledge_feedback', ['search_request_id', 'question_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_knowledge_feedback_source', 'knowledge_feedback', ['source'], unique=False, postgresql_using='btree')
    op.create_table('search_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_request_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=500), nullable=False),
    sa.Column('rating', postgresql.ENUM('LIKE', 'DISLIKE', name='rating_enum', create_type=False), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_request_id'], ['search_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_request_id', 'question_id', name='unique_search_feedback_request_question')
    )
    op.create_index('idx_search_feedback_comment_gin', 'search_feedback', ['comment'], unique=False, postgresql_using='gin', postgresql_ops={'comment': 'gin_trgm_ops'})
    op.create_index('idx_search_feedback_created_at_asc', 'search_feedback', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'ASC'})
    op.create_index('idx_search_feedback_created_at_desc', 'search_feedback', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_search_feedback_id_search_request_id', 'search_feedback', ['id', 'search_request_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_feedback_modified_at_asc', 'search_feedback', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'ASC'})
    op.create_index('idx_search_feedback_modified_at_desc', 'search_feedback', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.create_index('idx_search_feedback_question_id', 'search_feedback', ['question_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_feedback_search_request_id', 'search_feedback', ['search_request_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_feedback_search_request_id_question_id', 'search_feedback', ['search_request_id', 'question_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_feedback_source', 'search_feedback', ['source'], unique=False, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_search_feedback_source', table_name='search_feedback', postgresql_using='btree')
    op.drop_index('idx_search_feedback_search_request_id_question_id', table_name='search_feedback', postgresql_using='btree')
    op.drop_index('idx_search_feedback_search_request_id', table_name='search_feedback', postgresql_using='btree')
    op.drop_index('idx_search_feedback_question_id', table_name='search_feedback', postgresql_using='btree')
    op.drop_index('idx_search_feedback_modified_at_desc', table_name='search_feedback', postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.drop_index('idx_search_feedback_modified_at_asc', table_name='search_feedback', postgresql_using='btree', postgresql_ops={'modified_at': 'ASC'})
    op.drop_index('idx_search_feedback_id_search_request_id', table_name='search_feedback', postgresql_using='btree')
    op.drop_index('idx_search_feedback_created_at_desc', table_name='search_feedback', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_search_feedback_created_at_asc', table_name='search_feedback', postgresql_using='btree', postgresql_ops={'created_at': 'ASC'})
    op.drop_index('idx_search_feedback_comment_gin', table_name='search_feedback', postgresql_using='gin', postgresql_ops={'comment': 'gin_trgm_ops'})
    op.drop_table('search_feedback')
    op.drop_index('idx_knowledge_feedback_source', table_name='knowledge_feedback', postgresql_using='btree')
    op.drop_index('idx_knowledge_feedback_search_request_id_question_id', table_name='knowledge_feedback', postgresql_using='btree')
    op.drop_index('idx_knowledge_feedback_search_request_id', table_name='knowledge_feedback', postgresql_using='btree')
    op.drop_index('idx_knowledge_feedback_question_id', table_name='knowledge_feedback', postgresql_using='btree')
    op.drop_index('idx_knowledge_feedback_modified_at_desc', table_name='knowledge_feedback', postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.drop_index('idx_knowledge_feedback_modified_at_asc', table_name='knowledge_feedback', postgresql_using='btree', postgresql_ops={'modified_at': 'ASC'})
    op.drop_index('idx_knowledge_feedback_id_search_request_id', table_name='knowledge_feedback', postgresql_using='btree')
    op.drop_index('idx_knowledge_feedback_created_at_desc', table_name='knowledge_feedback', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_knowledge_feedback_created_at_asc', table_name='knowledge_feedback', postgresql_using='btree', postgresql_ops={'created_at': 'ASC'})
    op.drop_index('idx_knowledge_feedback_comment_gin', table_name='knowledge_feedback', postgresql_using='gin', postgresql_ops={'comment': 'gin_trgm_ops'})
    op.drop_table('knowledge_feedback')
    op.drop_index('ix_search_request_weight_lex', table_name='search_request', postgresql_using='btree')
    op.drop_index('ix_search_request_weight_dense', table_name='search_request', postgresql_using='btree')
    op.drop_index('ix_search_request_weight_ce', table_name='search_request', postgresql_using='btree')
    op.drop_index('ix_search_request_top_k', table_name='search_request', postgresql_using='btree')
    op.drop_index('ix_search_request_search_start_time_desc', table_name='search_request', postgresql_using='btree', postgresql_ops={'search_start_time': 'DESC'})
    op.drop_index('ix_search_request_search_start_time_asc', table_name='search_request', postgresql_using='btree', postgresql_ops={'search_start_time': 'ASC'})
    op.drop_index('ix_search_request_search_execution_time', table_name='search_request', postgresql_using='btree')
    op.drop_index('ix_search_request_results_jsonb_path', table_name='search_request', postgresql_using='gin', postgresql_ops={'results': 'jsonb_path_ops'})
    op.drop_index('ix_search_request_reranker_time', table_name='search_request', postgresql_using='btree')
    op.drop_index('ix_search_request_reranker_name_gin_trgm', table_name='search_request', postgresql_using='gin', postgresql_ops={'reranker_name': 'gin_trgm_ops'})
    op.drop_index('ix_search_request_reranker_enable', table_name='search_request', postgresql_using='btree')
    op.drop_index('ix_search_request_query_norm_time', table_name='search_request', postgresql_using='btree')
    op.drop_index('ix_search_request_query_gin_trgm', table_name='search_request', postgresql_using='gin', postgresql_ops={'query': 'gin_trgm_ops'})
    op.drop_index('ix_search_request_modified_at_desc', table_name='search_request', postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.drop_index('ix_search_request_modified_at_asc', table_name='search_request', postgresql_using='btree', postgresql_ops={'modified_at': 'ASC'})
    op.drop_index('ix_search_request_model_name_gin_trgm', table_name='search_request', postgresql_using='gin', postgresql_ops={'model_name': 'gin_trgm_ops'})
    op.drop_index('ix_search_request_lex_top_k', table_name='search_request', postgresql_using='btree')
    op.drop_index('ix_search_request_lex_search_time', table_name='search_request', postgresql_using='btree')
    op.drop_index('ix_search_request_lex_enable', table_name='search_request', postgresql_using='btree')
    op.drop_index('ix_search_request_lex_candidate_gin_trgm', table_name='search_request', postgresql_using='gin', postgresql_ops={'lex_candidate': 'gin_trgm_ops'})
    op.drop_index('ix_search_request_full_execution_time', table_name='search_request', postgresql_using='btree')
    op.drop_index('ix_search_request_from_cache', table_name='search_request', postgresql_using='btree')
    op.drop_index('ix_search_request_dense_top_k', table_name='search_request', postgresql_using='btree')
    op.drop_index('ix_search_request_dense_search_time', table_name='search_request', postgresql_using='btree')
    op.drop_index('ix_search_request_created_at_desc', table_name='search_request', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('ix_search_request_created_at_asc', table_name='search_request', postgresql_using='btree', postgresql_ops={'created_at': 'ASC'})
    op.drop_table('search_request')
    sa.Enum('LIKE', 'DISLIKE', name='rating_enum').drop(op.get_bind())
    # ### end Alembic commands ###
