"""search_entry_etc

Revision ID: 5bded9984796
Revises: be6da433bd0a
Create Date: 2026-04-10 13:28:40.609407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bded9984796'
down_revision: Union[str, None] = 'be6da433bd0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='unique_component_name')
    )
    op.create_index('idx_component_created_at_asc', 'component', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'ASC'})
    op.create_index('idx_component_created_at_desc', 'component', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_component_modified_at_asc', 'component', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'ASC'})
    op.create_index('idx_component_modified_at_desc', 'component', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.create_index('idx_component_name', 'component', ['name'], unique=False, postgresql_using='btree')
    op.create_index('idx_component_name_gin_trgm', 'component', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='unique_product_name')
    )
    op.create_index('idx_product_created_at_asc', 'product', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'ASC'})
    op.create_index('idx_product_created_at_desc', 'product', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_product_modified_at_asc', 'product', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'ASC'})
    op.create_index('idx_product_modified_at_desc', 'product', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.create_index('idx_product_name', 'product', ['name'], unique=False, postgresql_using='btree')
    op.create_index('idx_product_name_gin_trgm', 'product', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='unique_role_name')
    )
    op.create_index('idx_role_created_at_asc', 'role', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'ASC'})
    op.create_index('idx_role_created_at_desc', 'role', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_role_modified_at_asc', 'role', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'ASC'})
    op.create_index('idx_role_modified_at_desc', 'role', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.create_index('idx_role_name', 'role', ['name'], unique=False, postgresql_using='btree')
    op.create_index('idx_role_name_gin_trgm', 'role', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='unique_source_name')
    )
    op.create_index('idx_source_created_at_asc', 'source', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'ASC'})
    op.create_index('idx_source_created_at_desc', 'source', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_source_modified_at_asc', 'source', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'ASC'})
    op.create_index('idx_source_modified_at_desc', 'source', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.create_index('idx_source_name', 'source', ['name'], unique=False, postgresql_using='btree')
    op.create_index('idx_source_name_gin_trgm', 'source', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('search_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_number', sa.String(length=500), nullable=False),
    sa.Column('page_id', sa.String(length=500), nullable=False),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.Column('is_second_line', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('question_markdown', sa.Text(), nullable=False),
    sa.Column('question_clean', sa.Text(), nullable=False),
    sa.Column('error_analysis_markdown', sa.Text(), nullable=False),
    sa.Column('error_analysis_clean', sa.Text(), nullable=False),
    sa.Column('answer_markdown', sa.Text(), nullable=False),
    sa.Column('answer_clean', sa.Text(), nullable=False),
    sa.Column('is_for_user', sa.Boolean(), nullable=False),
    sa.Column('jira', sa.String(length=2000), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'knowledge_number', 'page_id', name='unique_search_entry_source_knowledge_page')
    )
    op.create_index('idx_search_entry_answer_clean_gin_trgm', 'search_entry', ['answer_clean'], unique=False, postgresql_using='gin', postgresql_ops={'answer_clean': 'gin_trgm_ops'})
    op.create_index('idx_search_entry_answer_markdown_gin_trgm', 'search_entry', ['answer_markdown'], unique=False, postgresql_using='gin', postgresql_ops={'answer_markdown': 'gin_trgm_ops'})
    op.create_index('idx_search_entry_component_id', 'search_entry', ['component_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_entry_created_at_asc', 'search_entry', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'ASC'})
    op.create_index('idx_search_entry_created_at_desc', 'search_entry', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_search_entry_error_analysis_clean_gin_trgm', 'search_entry', ['error_analysis_clean'], unique=False, postgresql_using='gin', postgresql_ops={'error_analysis_clean': 'gin_trgm_ops'})
    op.create_index('idx_search_entry_error_analysis_markdown_gin_trgm', 'search_entry', ['error_analysis_markdown'], unique=False, postgresql_using='gin', postgresql_ops={'error_analysis_markdown': 'gin_trgm_ops'})
    op.create_index('idx_search_entry_id_component_id', 'search_entry', ['id', 'component_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_entry_id_product_id', 'search_entry', ['id', 'product_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_entry_id_role_id', 'search_entry', ['id', 'role_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_entry_id_source_id', 'search_entry', ['id', 'source_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_entry_is_actual', 'search_entry', ['is_actual'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_entry_is_for_user', 'search_entry', ['is_for_user'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_entry_is_second_line', 'search_entry', ['is_second_line'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_entry_jira', 'search_entry', ['jira'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_entry_jira_gin_trgm', 'search_entry', ['jira'], unique=False, postgresql_using='gin', postgresql_ops={'jira': 'gin_trgm_ops'})
    op.create_index('idx_search_entry_knowledge_number', 'search_entry', ['knowledge_number'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_entry_knowledge_number_gin_trgm', 'search_entry', ['knowledge_number'], unique=False, postgresql_using='gin', postgresql_ops={'knowledge_number': 'gin_trgm_ops'})
    op.create_index('idx_search_entry_modified_at_asc', 'search_entry', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'ASC'})
    op.create_index('idx_search_entry_modified_at_desc', 'search_entry', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.create_index('idx_search_entry_page_id', 'search_entry', ['page_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_entry_page_id_gin_trgm', 'search_entry', ['page_id'], unique=False, postgresql_using='gin', postgresql_ops={'page_id': 'gin_trgm_ops'})
    op.create_index('idx_search_entry_product_id', 'search_entry', ['product_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_entry_question_clean_gin_trgm', 'search_entry', ['question_clean'], unique=False, postgresql_using='gin', postgresql_ops={'question_clean': 'gin_trgm_ops'})
    op.create_index('idx_search_entry_question_markdown_gin_trgm', 'search_entry', ['question_markdown'], unique=False, postgresql_using='gin', postgresql_ops={'question_markdown': 'gin_trgm_ops'})
    op.create_index('idx_search_entry_role_id', 'search_entry', ['role_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_entry_role_id_product_id_component_id', 'search_entry', ['role_id', 'product_id', 'component_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_entry_source_id', 'search_entry', ['source_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_entry_source_id_knowledge_number', 'search_entry', ['source_id', 'knowledge_number'], unique=False, postgresql_using='btree')
    op.create_index('idx_search_entry_source_id_knowledge_number_page_id', 'search_entry', ['source_id', 'knowledge_number', 'page_id'], unique=False, postgresql_using='btree')
    op.drop_index(op.f('idx_knowledge_feedback_created_at_desc'), table_name='knowledge_feedback')
    op.create_index('idx_knowledge_feedback_created_at_desc', 'knowledge_feedback', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_knowledge_feedback_modified_at_desc'), table_name='knowledge_feedback')
    op.create_index('idx_knowledge_feedback_modified_at_desc', 'knowledge_feedback', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.drop_index(op.f('idx_search_feedback_created_at_desc'), table_name='search_feedback')
    op.create_index('idx_search_feedback_created_at_desc', 'search_feedback', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_search_feedback_modified_at_desc'), table_name='search_feedback')
    op.create_index('idx_search_feedback_modified_at_desc', 'search_feedback', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.drop_index(op.f('ix_search_request_created_at_desc'), table_name='search_request')
    op.create_index('ix_search_request_created_at_desc', 'search_request', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('ix_search_request_modified_at_desc'), table_name='search_request')
    op.create_index('ix_search_request_modified_at_desc', 'search_request', ['modified_at'], unique=False, postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.drop_index(op.f('ix_search_request_search_start_time_desc'), table_name='search_request')
    op.create_index('ix_search_request_search_start_time_desc', 'search_request', ['search_start_time'], unique=False, postgresql_using='btree', postgresql_ops={'search_start_time': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search_request_search_start_time_desc', table_name='search_request', postgresql_using='btree', postgresql_ops={'search_start_time': 'DESC'})
    op.create_index(op.f('ix_search_request_search_start_time_desc'), 'search_request', [sa.literal_column('search_start_time DESC')], unique=False)
    op.drop_index('ix_search_request_modified_at_desc', table_name='search_request', postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.create_index(op.f('ix_search_request_modified_at_desc'), 'search_request', [sa.literal_column('modified_at DESC')], unique=False)
    op.drop_index('ix_search_request_created_at_desc', table_name='search_request', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_search_request_created_at_desc'), 'search_request', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_search_feedback_modified_at_desc', table_name='search_feedback', postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.create_index(op.f('idx_search_feedback_modified_at_desc'), 'search_feedback', [sa.literal_column('modified_at DESC')], unique=False)
    op.drop_index('idx_search_feedback_created_at_desc', table_name='search_feedback', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_search_feedback_created_at_desc'), 'search_feedback', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_knowledge_feedback_modified_at_desc', table_name='knowledge_feedback', postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.create_index(op.f('idx_knowledge_feedback_modified_at_desc'), 'knowledge_feedback', [sa.literal_column('modified_at DESC')], unique=False)
    op.drop_index('idx_knowledge_feedback_created_at_desc', table_name='knowledge_feedback', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_knowledge_feedback_created_at_desc'), 'knowledge_feedback', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_search_entry_source_id_knowledge_number_page_id', table_name='search_entry', postgresql_using='btree')
    op.drop_index('idx_search_entry_source_id_knowledge_number', table_name='search_entry', postgresql_using='btree')
    op.drop_index('idx_search_entry_source_id', table_name='search_entry', postgresql_using='btree')
    op.drop_index('idx_search_entry_role_id_product_id_component_id', table_name='search_entry', postgresql_using='btree')
    op.drop_index('idx_search_entry_role_id', table_name='search_entry', postgresql_using='btree')
    op.drop_index('idx_search_entry_question_markdown_gin_trgm', table_name='search_entry', postgresql_using='gin', postgresql_ops={'question_markdown': 'gin_trgm_ops'})
    op.drop_index('idx_search_entry_question_clean_gin_trgm', table_name='search_entry', postgresql_using='gin', postgresql_ops={'question_clean': 'gin_trgm_ops'})
    op.drop_index('idx_search_entry_product_id', table_name='search_entry', postgresql_using='btree')
    op.drop_index('idx_search_entry_page_id_gin_trgm', table_name='search_entry', postgresql_using='gin', postgresql_ops={'page_id': 'gin_trgm_ops'})
    op.drop_index('idx_search_entry_page_id', table_name='search_entry', postgresql_using='btree')
    op.drop_index('idx_search_entry_modified_at_desc', table_name='search_entry', postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.drop_index('idx_search_entry_modified_at_asc', table_name='search_entry', postgresql_using='btree', postgresql_ops={'modified_at': 'ASC'})
    op.drop_index('idx_search_entry_knowledge_number_gin_trgm', table_name='search_entry', postgresql_using='gin', postgresql_ops={'knowledge_number': 'gin_trgm_ops'})
    op.drop_index('idx_search_entry_knowledge_number', table_name='search_entry', postgresql_using='btree')
    op.drop_index('idx_search_entry_jira_gin_trgm', table_name='search_entry', postgresql_using='gin', postgresql_ops={'jira': 'gin_trgm_ops'})
    op.drop_index('idx_search_entry_jira', table_name='search_entry', postgresql_using='btree')
    op.drop_index('idx_search_entry_is_second_line', table_name='search_entry', postgresql_using='btree')
    op.drop_index('idx_search_entry_is_for_user', table_name='search_entry', postgresql_using='btree')
    op.drop_index('idx_search_entry_is_actual', table_name='search_entry', postgresql_using='btree')
    op.drop_index('idx_search_entry_id_source_id', table_name='search_entry', postgresql_using='btree')
    op.drop_index('idx_search_entry_id_role_id', table_name='search_entry', postgresql_using='btree')
    op.drop_index('idx_search_entry_id_product_id', table_name='search_entry', postgresql_using='btree')
    op.drop_index('idx_search_entry_id_component_id', table_name='search_entry', postgresql_using='btree')
    op.drop_index('idx_search_entry_error_analysis_markdown_gin_trgm', table_name='search_entry', postgresql_using='gin', postgresql_ops={'error_analysis_markdown': 'gin_trgm_ops'})
    op.drop_index('idx_search_entry_error_analysis_clean_gin_trgm', table_name='search_entry', postgresql_using='gin', postgresql_ops={'error_analysis_clean': 'gin_trgm_ops'})
    op.drop_index('idx_search_entry_created_at_desc', table_name='search_entry', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_search_entry_created_at_asc', table_name='search_entry', postgresql_using='btree', postgresql_ops={'created_at': 'ASC'})
    op.drop_index('idx_search_entry_component_id', table_name='search_entry', postgresql_using='btree')
    op.drop_index('idx_search_entry_answer_markdown_gin_trgm', table_name='search_entry', postgresql_using='gin', postgresql_ops={'answer_markdown': 'gin_trgm_ops'})
    op.drop_index('idx_search_entry_answer_clean_gin_trgm', table_name='search_entry', postgresql_using='gin', postgresql_ops={'answer_clean': 'gin_trgm_ops'})
    op.drop_table('search_entry')
    op.drop_index('idx_source_name_gin_trgm', table_name='source', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('idx_source_name', table_name='source', postgresql_using='btree')
    op.drop_index('idx_source_modified_at_desc', table_name='source', postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.drop_index('idx_source_modified_at_asc', table_name='source', postgresql_using='btree', postgresql_ops={'modified_at': 'ASC'})
    op.drop_index('idx_source_created_at_desc', table_name='source', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_source_created_at_asc', table_name='source', postgresql_using='btree', postgresql_ops={'created_at': 'ASC'})
    op.drop_table('source')
    op.drop_index('idx_role_name_gin_trgm', table_name='role', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('idx_role_name', table_name='role', postgresql_using='btree')
    op.drop_index('idx_role_modified_at_desc', table_name='role', postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.drop_index('idx_role_modified_at_asc', table_name='role', postgresql_using='btree', postgresql_ops={'modified_at': 'ASC'})
    op.drop_index('idx_role_created_at_desc', table_name='role', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_role_created_at_asc', table_name='role', postgresql_using='btree', postgresql_ops={'created_at': 'ASC'})
    op.drop_table('role')
    op.drop_index('idx_product_name_gin_trgm', table_name='product', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('idx_product_name', table_name='product', postgresql_using='btree')
    op.drop_index('idx_product_modified_at_desc', table_name='product', postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.drop_index('idx_product_modified_at_asc', table_name='product', postgresql_using='btree', postgresql_ops={'modified_at': 'ASC'})
    op.drop_index('idx_product_created_at_desc', table_name='product', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_product_created_at_asc', table_name='product', postgresql_using='btree', postgresql_ops={'created_at': 'ASC'})
    op.drop_table('product')
    op.drop_index('idx_component_name_gin_trgm', table_name='component', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('idx_component_name', table_name='component', postgresql_using='btree')
    op.drop_index('idx_component_modified_at_desc', table_name='component', postgresql_using='btree', postgresql_ops={'modified_at': 'DESC'})
    op.drop_index('idx_component_modified_at_asc', table_name='component', postgresql_using='btree', postgresql_ops={'modified_at': 'ASC'})
    op.drop_index('idx_component_created_at_desc', table_name='component', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_component_created_at_asc', table_name='component', postgresql_using='btree', postgresql_ops={'created_at': 'ASC'})
    op.drop_table('component')
    # ### end Alembic commands ###
